// <auto-generated />
namespace Homework_7_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SetLastNameMaxLengthAndRequiredInStudnetsTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetLastNameMaxLengthAndRequiredInStudnetsTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202402231842268_SetLastNameMaxLengthAndRequiredInStudnetsTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
